// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: car.proto

package proto;

public final class CarOuterClass {
  private CarOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_Empty_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Car_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_Car_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_CarList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_CarList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_CarRequestId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_CarRequestId_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tcar.proto\022\005proto\"\007\n\005Empty\"U\n\003Car\022\n\n\002id" +
      "\030\001 \001(\t\022\014\n\004Nome\030\002 \001(\t\022\022\n\nFabricacao\030\003 \001(\t" +
      "\022\021\n\tanoModelo\030\004 \001(\t\022\r\n\005preco\030\005 \001(\t\"\"\n\007Ca" +
      "rList\022\027\n\003car\030\001 \003(\0132\n.proto.Car\"\032\n\014CarReq" +
      "uestId\022\n\n\002id\030\001 \001(\t2\325\001\n\nCarService\022&\n\004Lis" +
      "t\022\014.proto.Empty\032\016.proto.CarList\"\000\022(\n\003Get" +
      "\022\023.proto.CarRequestId\032\n.proto.Car\"\000\022\"\n\006C" +
      "reate\022\n.proto.Car\032\n.proto.Car\"\000\022\"\n\006Updat" +
      "e\022\n.proto.Car\032\n.proto.Car\"\000\022-\n\006Delete\022\023." +
      "proto.CarRequestId\032\014.proto.Empty\"\000B\002P\001b\006" +
      "proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_proto_Empty_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_Empty_descriptor,
        new java.lang.String[] { });
    internal_static_proto_Car_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_Car_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_Car_descriptor,
        new java.lang.String[] { "Id", "Nome", "Fabricacao", "AnoModelo", "Preco", });
    internal_static_proto_CarList_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_proto_CarList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_CarList_descriptor,
        new java.lang.String[] { "Car", });
    internal_static_proto_CarRequestId_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_proto_CarRequestId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_CarRequestId_descriptor,
        new java.lang.String[] { "Id", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
