// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: car.proto

package proto;

public interface CarOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.Car)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string Nome = 2;</code>
   */
  java.lang.String getNome();
  /**
   * <code>string Nome = 2;</code>
   */
  com.google.protobuf.ByteString
      getNomeBytes();

  /**
   * <code>string Fabricacao = 3;</code>
   */
  java.lang.String getFabricacao();
  /**
   * <code>string Fabricacao = 3;</code>
   */
  com.google.protobuf.ByteString
      getFabricacaoBytes();

  /**
   * <code>string anoModelo = 4;</code>
   */
  java.lang.String getAnoModelo();
  /**
   * <code>string anoModelo = 4;</code>
   */
  com.google.protobuf.ByteString
      getAnoModeloBytes();

  /**
   * <code>string preco = 5;</code>
   */
  java.lang.String getPreco();
  /**
   * <code>string preco = 5;</code>
   */
  com.google.protobuf.ByteString
      getPrecoBytes();
}
